config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    resources :purchases, only: [:new, :create]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :condition
  belongs_to_active_hash :shipping_fee
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shipping_schedule

  belongs_to :user
  has_one_attached :image
  has_many :comments
  has_one :purchase
  has_one :address

  validates :image, :name, :detail, presence: true

  with_options numericality: {
    other_than: 0,
    message: "can't be blank"
  } do
    validates :category_id
    validates :condition_id
    validates :shipping_fee_id
    validates :prefecture_id
    validates :shipping_schedule_id
  end

  validates :price, numericality: {
    greater_than_or_equal_to: 300,
    less_than_or_equal_to: 9_999_999,
    message: 'is out of setting range'
  }
  validates :price, format: {
    with: /\A[0-9]+\z/,
    message: 'is invalid. Input half-width characters.'
  }
  validates :price, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :redirect_to_sign_in, unless: :current_user, except: [:index, :show]
  before_action :item_find, only: [:show, :destroy, :edit, :update]

  def index
    @items = Item.includes(:user)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item
    else
      render :new
    end
  end

  def show
    if user_signed_in?
      redirect_to '/' if @item.user_id == current_user.id && @item.sold_out
    end
    @text = @item.detail.split(/\r\n|\r|\n/)
  end

  def destroy
    if @item.destroy
      redirect_to @item
    else
      render :show
    end
  end

  def edit
    render :show unless @item.user_id == current_user.id
  end

  def update
    if @item.update(item_params)
      redirect_to @item
    else
      render :edit
    end
  end

  private

  def item_find
    @item = Item.find(params[:id])
  end

  def redirect_to_sign_in
    redirect_to new_user_session_path
  end

  def item_params
    params.require(:item).permit(
      :name, :detail,
      :category_id,
      :condition_id,
      :shipping_fee_id, :prefecture_id, :shipping_schedule_id,
      :price,
      :image
    ).merge(user_id: current_user.id, sold_out: false)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>

  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%= render 'shared/error_messages', model: @item %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%= form_with model: @item, local: true do |f| %>
      <%# 出品画像 %>
      <%= render partial: 'shared/post_form/image', locals: { f: f } %>
      <%# /出品画像 %>

      <%# 商品名と商品説明 %>
      <%= render partial: 'shared/post_form/name_detail', locals: { f: f } %>
      <%# /商品名と商品説明 %>

      <%# 商品の詳細(category, condition) %>
      <%= render partial: 'shared/post_form/cat_con', locals: { f: f } %>
      <%# /商品の詳細 %>

      <%# 配送について %>
      <%= render partial: 'shared/post_form/shipping', locals: { f: f } %>
      <%# /配送について %>

      <%# 販売価格 %>
      <%= render partial: 'shared/post_form/price', locals: { f: f } %>
      <%# /販売価格 %>

      <%# 注意書き %>
      <%= render 'shared/post_form/caution' %>
      <%# /注意書き %>

      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <% unless @item.id %>
          <%= f.submit "出品する" ,class:"sell-btn" %>
          <%=link_to 'もどる', root_path, class:"back-btn" %>
        <% else %>
          <%= f.submit "変更する" ,class:"sell-btn" %>
          <%=link_to 'もどる', item_path(@item), class:"back-btn" %>
        <% end %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>
<%= render 'items/new' %>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <%= render 'shared/index/index_1' %>
  <%# //画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <%= render 'shared/index/index_2' %>
  <%# //FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <%= render 'shared/index/index_3' %>
  <%# //画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <%= render 'shared/index/index_4' %>
  <%# //FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%= link_to '新規投稿商品', "#", class: "subtitle" %>

    <ul class='item-lists'>
      <% if @items %>
        <% @items.each do |item| %>
          <%= render partial: 'shared/index/itemlist', locals: {item: item} %>
        <% end %>
      <% else %>
        <%# 商品がない場合のダミー %>
        <%= render 'shared/index/index_5' %>
        <%= render 'shared/index/index_6' %>
        <%# //商品がない場合のダミー %>
      <% end %>
    </ul>
  </div>
  <%# //商品一覧 %>
</div>

<div class='purchase-btn'>
  <span class='purchase-btn-text'>出品する</span>
  <a href="/items/new">
    <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </a>
</div>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<%= render 'items/new' %>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>

    <div class='item-img-content'>
      <%= image_tag @item.image, class:"item-box-img" %>
      <%# 商品が売れている場合は、sould outの表示をしましょう。 %>
      <% if @item.sold_out %>
        <div class='sold-out'>
          <span>Sold Out!!</span>
        </div>
      <% end %>
      <%# //商品が売れている場合は、sould outの表示をしましょう。 %>
    </div>

    <div class="item-price-box">
      <span class="item-price">
        ¥ <%= @item.price %>
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>
    </div>

    <% if user_signed_in? %>
      <% if current_user.id == @item.user_id %>
        <%= link_to '商品の編集', edit_item_path(@item), class: "item-red-btn" %>
        <p class='or-text'>or</p>
        <%= link_to '削除', item_path(@item), method: :delete, class:'item-destroy' %>
      <% else %>
        <% unless @item.sold_out %>
          <%= link_to '購入画面に進む', new_item_purchase_path(@item) ,class:"item-red-btn"%>
        <% end %>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span>商品説明</span>
    </div>

    <div class="item-detail">
      <% @text.each do |text| %>
        <% if text == '' %>
          <br />
        <% else %>
          <p style="font-size: 24px;">
            <%= text %>
          </p>
        <% end %>
      <% end %>
    </div>
    <%= render 'shared/item_detail' %>

    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>

      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>

      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>

      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>

  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class='another-item'><%= "商品のカテゴリー名" %>をもっと見る</a>
</div>

<%= render "shared/footer" %>